default_install_hook_types:
  - pre-commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--extend-select=I, --fix]
      - id: ruff-format
        args: [--line-length=100]

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        language: python
        entry: ty check .
        pass_filenames: false
        args: [--python=.venv/]
        additional_dependencies: [ty]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.2
    hooks:
      - id: uv-lock

  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v3.3.0
    hooks:
      - id: complexipy
        args: [--details=low]

  - repo: local
    hooks:
      - id: skylos-check
        name: skylos check
        language: python
        pass_filenames: false
        entry: |
          python -c "
          import sys,subprocess
          r=subprocess.run(['skylos','.'],capture_output=True,text=True)
          f=[]
          for l in r.stdout.split('\n'):
              if 'Add this badge' in l:l=l.split('Add this badge')[0]
              if not any(x in l for x in ['type=','📁 Excluding','```markdown','![Dead Code:','```']):f.append(l)
          print('\n'.join(f))
          sys.exit(0 if '100% dead code free' in r.stdout else 1)
          "
